import { all } from "redux-saga/effects";
import {
  previewActionImgList,
  previewAddCommentAction,
  previewAddImagesAction,
  previewAddUserAction,
  previewCommentInfoAction,
  previewDeleteCreatedImageAction,
  previewDeleteSavedImageAction,
  previewDeleteUserAction,
  previewGetUserListAction,
  previewImgInfoAction,
  previewListOfCreatedImageAction,
  previewListOfSavedImageAction,
  previewLoginAction,
  // previewRefreshTokenAction,
  previewSaveImageAction,
  previewSearchAction,
  previewSignupAction,
  previewUpdateUserAction,
  previewUpdateUserInfoAction,
} from "./capstoneSaga";

export default function* rootSaga() {
  yield all([
    previewActionImgList(),
    previewLoginAction(),
    previewSignupAction(),
    previewSearchAction(),
    previewImgInfoAction(),
    previewCommentInfoAction(),
    previewAddCommentAction(),
    previewSaveImageAction(),
    previewAddImagesAction(),
    previewUpdateUserInfoAction(),
    previewListOfSavedImageAction(),
    previewDeleteSavedImageAction(),
    previewListOfCreatedImageAction(),
    previewDeleteCreatedImageAction(),
    // previewRefreshTokenAction(),
    previewGetUserListAction(),
    previewDeleteUserAction(),
    previewAddUserAction(),
    previewUpdateUserAction(),
  ]);
}
