const BASE_IMG_URL = "http://localhost:8080";

const GET_IMG_LIST_SAGA = "GET_IMG_LIST_SAGA";
const GET_IMG_LIST = "GET_IMG_LIST";

const POST_LOGIN_SAGA = "POST_LOGIN_SAGA";
const POST_LOGIN = "POST_LOGIN";

const POST_SIGNUP_SAGA = "POST_SIGNUP_SAGA";
const POST_SIGNUP = "POST_SIGNUP";

const SEARCH_IMAGE_SAGA = "SEARCH_IMAGE_SAGA";
const SEARCH_IMAGE = "SEARCH_IMAGE";

const GET_IMG_INFO_SAGA = "GET_IMG_INFO_SAGA";
const GET_IMG_INFO = "GET_IMG_INFO";

const GET_COMMENT_INFO_SAGA = "GET_COMMENT_INFO_SAGA";
const GET_COMMENT_INFO = "GET_COMMENT_INFO";

const ADD_COMMENT_SAGA = "ADD_COMMENT_SAGA";
const ADD_COMMENT = "ADD_COMMENT";

const SAVE_IMAGE_SAGA = "SAVE_IMAGE_SAGA";
const SAVE_IMAGE = "SAVE_IMAGE";
const DELETE_SAVED_IMAGE_SAGA = "DELETE_SAVED_IMAGE_SAGA";
const DELETE_SAVED_IMAGE = "DELETE_SAVED_IMAGE";

const SWITCH_TAB = "SWITCH_TAB";
const SELECT_TAB = "SELECT_TAB";

const UPLOAD_IMAGES = "UPLOAD_IMAGES";

const ADD_IMAGES_SAGA = "ADD_IMAGES_SAGA";
const ADD_IMAGES = "ADD_IMAGES";
const ADD_IMAGES_SUCCESS = "ADD_IMAGES_SUCCESS";

const IS_HOVERING = "IS_HOVERING";
const IS_HOVERING_SAVED_IMAGE = "IS_HOVERING";
const IS_HOVERING_CREATED_IMAGE = "IS_HOVERING_CREATED_IMAGE";

const DELETE_IMAGE = "DELETE_IMAGE";

const USER_INFO_SAGA = "USER_INFO_SAGA";
const UPDATE_USER_INFO = "UPDATE_USER_INFO";

const GET_SAVED_IMAGE_SAGA = "GET_SAVED_IMAGE_SAGA";
const GET_SAVED_IMAGE = "GET_SAVED_IMAGE";

const GET_CREATED_IMAGE_SAGA = "GET_CREATED_IMAGE_SAGA";
const GET_CREATED_IMAGE = "GET_CREATED_IMAGE";

export {
  BASE_IMG_URL,
  GET_IMG_LIST_SAGA,
  GET_IMG_LIST,
  POST_LOGIN_SAGA,
  POST_LOGIN,
  POST_SIGNUP_SAGA,
  POST_SIGNUP,
  SEARCH_IMAGE_SAGA,
  SEARCH_IMAGE,
  GET_IMG_INFO_SAGA,
  GET_IMG_INFO,
  GET_COMMENT_INFO_SAGA,
  GET_COMMENT_INFO,
  ADD_COMMENT_SAGA,
  ADD_COMMENT,
  SAVE_IMAGE_SAGA,
  SAVE_IMAGE,
  DELETE_SAVED_IMAGE_SAGA,
  DELETE_SAVED_IMAGE,
  SWITCH_TAB,
  SELECT_TAB,
  UPLOAD_IMAGES,
  ADD_IMAGES_SAGA,
  ADD_IMAGES,
  ADD_IMAGES_SUCCESS,
  IS_HOVERING,
  IS_HOVERING_SAVED_IMAGE,
  IS_HOVERING_CREATED_IMAGE,
  DELETE_IMAGE,
  USER_INFO_SAGA,
  UPDATE_USER_INFO,
  GET_SAVED_IMAGE_SAGA,
  GET_SAVED_IMAGE,
  GET_CREATED_IMAGE_SAGA,
  GET_CREATED_IMAGE
};
