const BASE_IMG_URL = "http://localhost:8080";

const GET_IMG_LIST_SAGA = "GET_IMG_LIST_SAGA";
const GET_IMG_LIST = "GET_IMG_LIST";

const POST_LOGIN_SAGA = "POST_LOGIN_SAGA";
const POST_LOGIN = "POST_LOGIN";

const POST_SIGNUP_SAGA = "POST_SIGNUP_SAGA";
const POST_SIGNUP = "POST_SIGNUP";

const SEARCH_IMAGE_SAGA = "SEARCH_IMAGE_SAGA";
const SEARCH_IMAGE = "SEARCH_IMAGE";

const GET_IMG_INFO_SAGA = "GET_IMG_INFO_SAGA";
const GET_IMG_INFO = "GET_IMG_INFO";

const GET_COMMENT_INFO_SAGA = "GET_COMMENT_INFO_SAGA";
const GET_COMMENT_INFO = "GET_COMMENT_INFO";

const ADD_COMMENT_SAGA = "ADD_COMMENT_SAGA";
const ADD_COMMENT = "ADD_COMMENT";

const SAVE_IMAGE_SAGA = "SAVE_IMAGE_SAGA";
const SAVE_IMAGE = "SAVE_IMAGE";

const SWITCH_TAB = "SWITCH_TAB";
const SELECT_TAB = "SELECT_TAB";

export {
  BASE_IMG_URL,
  GET_IMG_LIST_SAGA,
  GET_IMG_LIST,
  POST_LOGIN_SAGA,
  POST_LOGIN,
  POST_SIGNUP_SAGA,
  POST_SIGNUP,
  SEARCH_IMAGE_SAGA,
  SEARCH_IMAGE,
  GET_IMG_INFO_SAGA,
  GET_IMG_INFO,
  GET_COMMENT_INFO_SAGA,
  GET_COMMENT_INFO,
  ADD_COMMENT_SAGA,
  ADD_COMMENT,
  SAVE_IMAGE_SAGA,
  SAVE_IMAGE,
  SWITCH_TAB,
  SELECT_TAB
};
