const BASE_IMG_URL = "http://localhost:8080";

const GET_IMG_LIST_SAGA = "GET_IMG_LIST_SAGA";
const GET_IMG_LIST = "GET_IMG_LIST";

const POST_LOGIN_SAGA = "POST_LOGIN_SAGA";
const POST_LOGIN = "POST_LOGIN";

const POST_SIGNUP_SAGA = "POST_SIGNUP_SAGA";
const POST_SIGNUP = "POST_SIGNUP";

const SEARCH_IMAGE_SAGE = "SEARCH_IMAGE_SAGE";
const SEARCH_IMAGE = "SEARCH_IMAGE";

export {
  BASE_IMG_URL,
  GET_IMG_LIST_SAGA,
  GET_IMG_LIST,
  POST_LOGIN_SAGA,
  POST_LOGIN,
  POST_SIGNUP_SAGA,
  POST_SIGNUP,
  SEARCH_IMAGE_SAGE,
  SEARCH_IMAGE
};
